server:
  port: 8081

spring:
  config:
    location: classpath:/config/jdbcConfig.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?netsafe&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    # 配置 DBMS 类型
    database: mysql
    # 配置开启自动更新表结构
    hibernate:
      ddl-auto: none
    # 配置是否将执行的 SQL 输出到日志
    show-sql: true


#mybatis:
#  扫描classpath下mapping中的映射配置文件，针对映射配置文件放到resources下
#  mapper-locations: classpath:/mapping/*.xml
#  type-aliases-package:
logging:
  level:
    root: warn
    com.blog: info
  file:
    name: logs/blog-pro.log
