spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  profiles:
    active: dev

server:
  error:
    path: /error

size:
  type: 6
  tag: 10
  blog: 8